version: 0.2
phases:
  install:
    commands:
      - ls -ltr
  pre_build:
    commands:
      - echo $base_image_id
      - assume_role_arn='arn:aws:iam::255679434152:role/human-role/a207947-PowerUser2'
      - env_name=dev
      - role_arn='arn:aws:iam::255679434152:role/human-role/a207947-PowerUser2'
      - role_session_name='packercodebuildjob'
      - echo "Assuming Role"
      - sh assume-role.sh $role_arn $role_session_name
      - export AWS_PROFILE=$role_session_name
      - asset_insight_id=`echo $CODEBUILD_BUILD_ID | awk -F '-' '{print $1}'`
      - echo $asset_insight_id
      - ls -ltr
      - aws sts get-caller-identity
      - ${!AWS_@}
      - aws sts get-caller-identity
      - pwd
  build:
    commands:
      - ls -ltr
  post_build:
    commands:
      - ls
      

